#!/bin/sh
# go to configfs directory for USB gadgets

SN=`awk '{ if ($1 == "serial_number") print $2 }' /boot/aqi-gadget-info`
PROD=`awk '{ if ($1 == "product") for (i=2;i<=NF;i++) printf "%s", $i OFS; }' /boot/aqi-gadget-info`
MANU=`awk '{ if ($1 == "manufacturer") for (i=2;i<=NF;i++) printf "%s", $i OFS; }' /boot/aqi-gadget-info`
HNAME=`awk '{ if ($1 == "hostname_base") print $2 }' /boot/aqi-gadget-info`
CURRENTNAME=`hostname`
TARGETNAME=$HNAME-$SN

if [ "$CURRENTNAME" = "$TARGETNAME" ]; then
   HOSTNAME_UPDATE=NO
else
   HOSTNAME_UPDATE=YES
   mount -o remount,rw /
   echo $TARGETNAME > /etc/hostname
   sed --in-place=bak "s/$CURRENTNAME/$TARGETNAME/" /etc/hosts
   mount -o remount,ro /
fi

cd /sys/kernel/config/usb_gadget

# create gadget directory and enter it
mkdir g1
cd g1

# USB ids
echo 0x1d6b > idVendor
echo 0x104 > idProduct

# USB strings, optional
mkdir strings/0x409 # US English, others rarely seen
echo $MANU > strings/0x409/manufacturer
echo $PROD > strings/0x409/product
echo $SN > strings/0x409/serialnumber

# create the (only) configuration
mkdir configs/c.1 # dot and number mandatory

# create the ethernet function
mkdir functions/ecm.usb0 
echo 32:71:15:18:ff:7a > functions/ecm.usb0/host_addr
echo 32:71:15:18:ff:7b > functions/ecm.usb0/dev_addr

# create mass_storage function
mkdir functions/mass_storage.0
echo 1 > functions/mass_storage.0/ro
echo 1 > functions/mass_storage.0/removable
echo /storage.fat32.dmg > functions/mass_storage.0/lun.0/file

# assign function to configuration
ln -s functions/ecm.usb0/ configs/c.1/
ln -s functions/mass_storage.0/ configs/c.1/

# bind!
udevadm settle -t 5 || :
ls /sys/class/udc > UDC 
ifup usb0

cd /home/pi/aqi-gadget
./display_connection.py 

ST=`cat /sys/devices/platform/soc/20980000.usb/udc/20980000.usb/state`
if [ "$ST" = "not attached" ]; then
    ifconfig usb0 down
else
    ifconfig wlan0 down
fi
