#!/bin/sh
# go to configfs directory for USB gadgets

cd /sys/kernel/config/usb_gadget

# create gadget directory and enter it
mkdir g1
cd g1

# USB ids
echo 0x1d6b > idVendor
echo 0x104 > idProduct

# USB strings, optional
mkdir strings/0x409 # US English, others rarely seen
echo "Absolute Garbage" > strings/0x409/manufacturer
echo "AQI Gadget" > strings/0x409/product
echo "sn0001" > strings/0x409/serialnumber

# create the (only) configuration
mkdir configs/c.1 # dot and number mandatory

# create the ethernet function
mkdir functions/ecm.usb0 
echo 32:71:15:18:ff:7a > functions/ecm.usb0/host_addr
echo 32:71:15:18:ff:7b > functions/ecm.usb0/dev_addr

# create mass_storage function
mkdir functions/mass_storage.0
echo 1 > functions/mass_storage.0/ro
echo 1 > functions/mass_storage.0/removable
echo /storage.fat32 > functions/mass_storage.0/lun.0/file

# assign function to configuration
ln -s functions/ecm.usb0/ configs/c.1/
ln -s functions/mass_storage.0/ configs/c.1/

# bind!
udevadm settle -t 5 || :
ls /sys/class/udc > UDC 
ifup usb0
